### PR TITLE
Rethinkdb

### PR DESCRIPTION
**Pull request by AndrewJWin**
Compatibility with RethinkDB has been achieved, all base commands are compatible, and function as intended.

### CODE REVIEW

**Comment by AndrewJWin** [comment]
Codacy hates me... __IT WORKS AND LOOKS FINE.__

**Comment by YorkAARGH** [comment]
Fix it @AndrewJWin lol, not having you mess up my beautiful code due to indent errors :P

**Comment by AndrewJWin** [comment]
Codacy complains about not being able to analyze it. I went in and fixed everything with proper spacing according to the master branch @YorkAARGH... If you'd like to go through it. That's fine, but I did what you asked...

**Comment by YorkAARGH** [comment]
I think it's because I didn't enable analysis on my end, I've done it now

**Comment by YorkAARGH** [comment]
Whilst I thank you for taking the time and effort to convert guidebot-class to use rethink, I cannot accept this PR due to the sheer number of files that I have had to fix due to code quality, if you could by chance resubmit a new PR with using the eslint file provided with this project, then I can happily accept the PR.

**Pull request closed without merging**
